// <auto-generated />
using LanguagePractice.DataAccess.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LanguagePracticeSite.Migrations
{
    [DbContext(typeof(WordDatabaseContext))]
    [Migration("20231207114359_RectifyVenirePastParticipal")]
    partial class RectifyVenirePastParticipal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LanguagePracticeSite.Models.Imperfect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnglishTranslation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstPersonPlural")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstPersonSingular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Infinitive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondPersonPlural")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondPersonSingular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdPersonPlural")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdPersonSingular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImperfectWords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnglishTranslation = "to see/look at",
                            FirstPersonPlural = "vedevamo",
                            FirstPersonSingular = "vedevo",
                            Infinitive = "vedere",
                            SecondPersonPlural = "vedevate",
                            SecondPersonSingular = "vedevi",
                            ThirdPersonPlural = "vedevano",
                            ThirdPersonSingular = "vedeva"
                        },
                        new
                        {
                            Id = 2,
                            EnglishTranslation = "to talk",
                            FirstPersonPlural = "parlavamo",
                            FirstPersonSingular = "parlavo",
                            Infinitive = "parlare",
                            SecondPersonPlural = "parlavate",
                            SecondPersonSingular = "parlavi",
                            ThirdPersonPlural = "parlavano",
                            ThirdPersonSingular = "parlava"
                        },
                        new
                        {
                            Id = 3,
                            EnglishTranslation = "to come",
                            FirstPersonPlural = "venivamo",
                            FirstPersonSingular = "venivo",
                            Infinitive = "venire",
                            SecondPersonPlural = "venivate",
                            SecondPersonSingular = "venivi",
                            ThirdPersonPlural = "venivano",
                            ThirdPersonSingular = "veniva"
                        },
                        new
                        {
                            Id = 4,
                            EnglishTranslation = "to do/make",
                            FirstPersonPlural = "facevamo",
                            FirstPersonSingular = "facevo",
                            Infinitive = "fare",
                            SecondPersonPlural = "facevate",
                            SecondPersonSingular = "facevi",
                            ThirdPersonPlural = "facevano",
                            ThirdPersonSingular = "facevama"
                        },
                        new
                        {
                            Id = 5,
                            EnglishTranslation = "to go",
                            FirstPersonPlural = "andavamo",
                            FirstPersonSingular = "andavo",
                            Infinitive = "andare",
                            SecondPersonPlural = "andavate",
                            SecondPersonSingular = "andavi",
                            ThirdPersonPlural = "andavano",
                            ThirdPersonSingular = "andava"
                        },
                        new
                        {
                            Id = 6,
                            EnglishTranslation = "to live",
                            FirstPersonPlural = "vivevamo",
                            FirstPersonSingular = "vivevo",
                            Infinitive = "vìvere",
                            SecondPersonPlural = "vivevate",
                            SecondPersonSingular = "vivevi",
                            ThirdPersonPlural = "vivevano",
                            ThirdPersonSingular = "viveva"
                        },
                        new
                        {
                            Id = 7,
                            EnglishTranslation = "to sleep",
                            FirstPersonPlural = "dormivamo",
                            FirstPersonSingular = "dormivo",
                            Infinitive = "dormire",
                            SecondPersonPlural = "dormivate",
                            SecondPersonSingular = "dormivi",
                            ThirdPersonPlural = "dormivano",
                            ThirdPersonSingular = "dormiva"
                        },
                        new
                        {
                            Id = 8,
                            EnglishTranslation = "to ask",
                            FirstPersonPlural = "chiedevamo",
                            FirstPersonSingular = "chiedevo",
                            Infinitive = "chiedere",
                            SecondPersonPlural = "chiedevate",
                            SecondPersonSingular = "chiedevi",
                            ThirdPersonPlural = "chiedevano",
                            ThirdPersonSingular = "chiedeva"
                        },
                        new
                        {
                            Id = 9,
                            EnglishTranslation = "to put",
                            FirstPersonPlural = "mettevamo",
                            FirstPersonSingular = "mettevo",
                            Infinitive = "mettere",
                            SecondPersonPlural = "mettevate",
                            SecondPersonSingular = "mettevi",
                            ThirdPersonPlural = "mettevano",
                            ThirdPersonSingular = "metteva"
                        },
                        new
                        {
                            Id = 10,
                            EnglishTranslation = "to dress",
                            FirstPersonPlural = "vestivamo",
                            FirstPersonSingular = "vestivo",
                            Infinitive = "vestire",
                            SecondPersonPlural = "vestivate",
                            SecondPersonSingular = "vestivi",
                            ThirdPersonPlural = "vestivano",
                            ThirdPersonSingular = "vestiva"
                        });
                });

            modelBuilder.Entity("LanguagePracticeSite.Models.PresentIndicative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnglishTranslation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstPersonPlural")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstPersonSingular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Infinitive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondPersonPlural")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondPersonSingular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdPersonPlural")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdPersonSingular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PresentIndicativeWords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnglishTranslation = "to do/make",
                            FirstPersonPlural = "facciamo",
                            FirstPersonSingular = "faccio",
                            Infinitive = "fare",
                            SecondPersonPlural = "fate",
                            SecondPersonSingular = "fai",
                            ThirdPersonPlural = "fanno",
                            ThirdPersonSingular = "fa"
                        },
                        new
                        {
                            Id = 2,
                            EnglishTranslation = "to see/look at",
                            FirstPersonPlural = "vediamo",
                            FirstPersonSingular = "vedo",
                            Infinitive = "vedere",
                            SecondPersonPlural = "vedete",
                            SecondPersonSingular = "vedi",
                            ThirdPersonPlural = "vedono",
                            ThirdPersonSingular = "vede"
                        },
                        new
                        {
                            Id = 3,
                            EnglishTranslation = "to talk",
                            FirstPersonPlural = "parliamo",
                            FirstPersonSingular = "parlo",
                            Infinitive = "parlare",
                            SecondPersonPlural = "parlate",
                            SecondPersonSingular = "parli",
                            ThirdPersonPlural = "parlano",
                            ThirdPersonSingular = "parla"
                        },
                        new
                        {
                            Id = 4,
                            EnglishTranslation = "to come",
                            FirstPersonPlural = "veniamo",
                            FirstPersonSingular = "vengo",
                            Infinitive = "venire",
                            SecondPersonPlural = "venite",
                            SecondPersonSingular = "vieni",
                            ThirdPersonPlural = "vengono",
                            ThirdPersonSingular = "viene"
                        },
                        new
                        {
                            Id = 5,
                            EnglishTranslation = "to go",
                            FirstPersonPlural = "andiamo",
                            FirstPersonSingular = "vado",
                            Infinitive = "andare",
                            SecondPersonPlural = "andate",
                            SecondPersonSingular = "vai",
                            ThirdPersonPlural = "vanno",
                            ThirdPersonSingular = "va"
                        },
                        new
                        {
                            Id = 6,
                            EnglishTranslation = "to live",
                            FirstPersonPlural = "viviamo",
                            FirstPersonSingular = "vivo",
                            Infinitive = "vìvere",
                            SecondPersonPlural = "vivete",
                            SecondPersonSingular = "vivi",
                            ThirdPersonPlural = "vivono",
                            ThirdPersonSingular = "vive"
                        },
                        new
                        {
                            Id = 7,
                            EnglishTranslation = "to sleep",
                            FirstPersonPlural = "dormiamo",
                            FirstPersonSingular = "dormo",
                            Infinitive = "dormire",
                            SecondPersonPlural = "dormite",
                            SecondPersonSingular = "dormi",
                            ThirdPersonPlural = "dormono",
                            ThirdPersonSingular = "dorme"
                        },
                        new
                        {
                            Id = 8,
                            EnglishTranslation = "to ask",
                            FirstPersonPlural = "chiediamo",
                            FirstPersonSingular = "chiedo",
                            Infinitive = "chiedere",
                            SecondPersonPlural = "chiedete",
                            SecondPersonSingular = "chiedi",
                            ThirdPersonPlural = "chiedono",
                            ThirdPersonSingular = "chiede"
                        },
                        new
                        {
                            Id = 9,
                            EnglishTranslation = "to put",
                            FirstPersonPlural = "mettiamo",
                            FirstPersonSingular = "metto",
                            Infinitive = "mettere",
                            SecondPersonPlural = "mettete",
                            SecondPersonSingular = "metti",
                            ThirdPersonPlural = "mettono",
                            ThirdPersonSingular = "mette"
                        },
                        new
                        {
                            Id = 10,
                            EnglishTranslation = "to dress",
                            FirstPersonPlural = "vestiamo",
                            FirstPersonSingular = "vesto",
                            Infinitive = "vestire",
                            SecondPersonPlural = "vestite",
                            SecondPersonSingular = "vesti",
                            ThirdPersonPlural = "vestono",
                            ThirdPersonSingular = "veste"
                        });
                });

            modelBuilder.Entity("LanguagePracticeSite.Models.PresentPerfect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnglishTranslation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstPersonPlural")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstPersonSingular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Infinitive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondPersonPlural")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondPersonSingular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdPersonPlural")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdPersonSingular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UsesEssere")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PresentPerfectPhrases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnglishTranslation = "to prepare",
                            FirstPersonPlural = "abbiamo preparato",
                            FirstPersonSingular = "ho preparato",
                            Infinitive = "preparare",
                            SecondPersonPlural = "avete preparato",
                            SecondPersonSingular = "hai preparato",
                            ThirdPersonPlural = "hanno preparato",
                            ThirdPersonSingular = "ha preparato",
                            UsesEssere = false
                        },
                        new
                        {
                            Id = 2,
                            EnglishTranslation = "to sell",
                            FirstPersonPlural = "abbiamo venduto",
                            FirstPersonSingular = "ho venduto",
                            Infinitive = "vendere",
                            SecondPersonPlural = "avete venduto",
                            SecondPersonSingular = "hai venduto",
                            ThirdPersonPlural = "hanno venduto",
                            ThirdPersonSingular = "ha venduto",
                            UsesEssere = false
                        },
                        new
                        {
                            Id = 3,
                            EnglishTranslation = "to go",
                            FirstPersonPlural = "siamo andati",
                            FirstPersonSingular = "sono andato",
                            Infinitive = "andare",
                            SecondPersonPlural = "siete andati",
                            SecondPersonSingular = "sei andato",
                            ThirdPersonPlural = "sono andati",
                            ThirdPersonSingular = "è andato",
                            UsesEssere = true
                        },
                        new
                        {
                            Id = 4,
                            EnglishTranslation = "to come",
                            FirstPersonPlural = "siamo venuti",
                            FirstPersonSingular = "sono venuto",
                            Infinitive = "venire",
                            SecondPersonPlural = "siete venuti",
                            SecondPersonSingular = "sei venuto",
                            ThirdPersonPlural = "sono venuti",
                            ThirdPersonSingular = "è venuto",
                            UsesEssere = true
                        },
                        new
                        {
                            Id = 5,
                            EnglishTranslation = "to do/make",
                            FirstPersonPlural = "abbiamo fatto",
                            FirstPersonSingular = "ho fatto",
                            Infinitive = "fare",
                            SecondPersonPlural = "avete fatto",
                            SecondPersonSingular = "hai fatto",
                            ThirdPersonPlural = "hanno fatto",
                            ThirdPersonSingular = "ha fatto",
                            UsesEssere = false
                        },
                        new
                        {
                            Id = 6,
                            EnglishTranslation = "to live",
                            FirstPersonPlural = "abbiamo vissuto",
                            FirstPersonSingular = "ho vissuto",
                            Infinitive = "vìvere",
                            SecondPersonPlural = "avete vissuto",
                            SecondPersonSingular = "hai vissuto",
                            ThirdPersonPlural = "hanno vissuto",
                            ThirdPersonSingular = "ha vissuto",
                            UsesEssere = false
                        },
                        new
                        {
                            Id = 7,
                            EnglishTranslation = "to sleep",
                            FirstPersonPlural = "abbiamo dormito",
                            FirstPersonSingular = "ho dormito",
                            Infinitive = "dormire",
                            SecondPersonPlural = "avete dormito",
                            SecondPersonSingular = "hai dormito",
                            ThirdPersonPlural = "hanno dormito",
                            ThirdPersonSingular = "ha dormito",
                            UsesEssere = false
                        },
                        new
                        {
                            Id = 8,
                            EnglishTranslation = "to ask",
                            FirstPersonPlural = "abbiamo chiesto",
                            FirstPersonSingular = "ho chiesto",
                            Infinitive = "chiedere",
                            SecondPersonPlural = "avete chiesto",
                            SecondPersonSingular = "hai chiesto",
                            ThirdPersonPlural = "hanno chiesto",
                            ThirdPersonSingular = "ha chiesto",
                            UsesEssere = false
                        },
                        new
                        {
                            Id = 9,
                            EnglishTranslation = "to put",
                            FirstPersonPlural = "abbiamo messo",
                            FirstPersonSingular = "ho messo",
                            Infinitive = "mettere",
                            SecondPersonPlural = "avete messo",
                            SecondPersonSingular = "hai messo",
                            ThirdPersonPlural = "hanno messo",
                            ThirdPersonSingular = "ha messo",
                            UsesEssere = false
                        },
                        new
                        {
                            Id = 10,
                            EnglishTranslation = "to dress",
                            FirstPersonPlural = "abbiamo vestito",
                            FirstPersonSingular = "ho vestito",
                            Infinitive = "vestire",
                            SecondPersonPlural = "avete vestito",
                            SecondPersonSingular = "hai vestito",
                            ThirdPersonPlural = "hanno vestito",
                            ThirdPersonSingular = "ha vestito",
                            UsesEssere = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
